/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mySidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: [
        {
          type: 'autogenerated',
          dirName: 'overview', // Generate sidebar slice from docs/preliminaries
        }
      ],
    },
    {
      type: 'category',
      label: 'Quickstart',
      items: [
        {
          type: 'autogenerated',
          dirName: 'quickstart', // Generate sidebar slice from docs/use-cases
        }
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        {
          type: 'autogenerated',
          dirName: 'get-started', // Generate sidebar slice from docs/get-started
        }
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          type: 'autogenerated',
          dirName: 'concepts', // Generate sidebar slice from docs/concepts
        }
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/restapi/index',
        'reference/cli',
        'reference/python/index',
        'reference/js/index',
        'reference/dotnet/index',
        'reference/java/index'
      ],
    },
    {
      type: 'category',
      label: 'Administration',
      items: [
        {
          type: 'autogenerated',
          dirName: 'administration', // Generate sidebar slice from docs/administration
        }
      ],
    },
    'questions'
  ]
};

module.exports = sidebars;
