{
  "openapi": "3.0.1",
  "info": {
    "title": "Lucidtech API",
    "version": "2024-02-02T13:36:49Z"
  },
  "servers": [
    {
      "url": "https://api.lucidtech.ai/{basePath}",
      "variables": {
        "basePath": {
          "default": "v1"
        }
      }
    }
  ],
  "paths": {
    "/appClients": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:read"
            ]
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:write"
            ]
          }
        ]
      }
    },
    "/appClients/{appClientId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:read"
            ]
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:read"
            ]
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:write"
            ]
          }
        ]
      }
    },
    "/assets": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:read"
            ]
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:write"
            ]
          }
        ]
      }
    },
    "/assets/{assetId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:read"
            ]
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:read"
            ]
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:write"
            ]
          }
        ]
      }
    },
    "/datasets": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/datasets:read"
            ]
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/datasets:write"
            ]
          }
        ]
      }
    },
    "/datasets/{datasetId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/datasets:read"
            ]
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/datasets:read"
            ]
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/datasets:write"
            ]
          }
        ]
      }
    },
    "/datasets/{datasetId}/transformations": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/organizations:read"
            ]
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/organizations:write"
            ]
          }
        ]
      }
    },
    "/datasets/{datasetId}/transformations/{transformationId}": {
      "delete": {
        "security": []
      },
      "options": {
      }
    },
    "/deploymentEnvironments": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/secrets:read"
            ]
          }
        ]
      },
      "options": {
      }
    },
    "/deploymentEnvironments/{deploymentEnvironmentId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/organizations:read"
            ]
          }
        ]
      },
      "options": {
      }
    },
    "/documents": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ]
      }
    },
    "/documents/{documentId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ]
      }
    },
    "/logs": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/logs:read"
            ]
          }
        ]
      },
      "options": {
      }
    },
    "/logs/{logId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/logs:read"
            ]
          }
        ]
      },
      "options": {
      }
    },
    "/models": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:write"
            ]
          }
        ]
      }
    },
    "/models/{modelId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:write"
            ]
          }
        ]
      }
    },
    "/models/{modelId}/dataBundles": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/databundles:read"
            ]
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/databundles:write"
            ]
          }
        ]
      }
    },
    "/models/{modelId}/dataBundles/{dataBundleId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/databundles:read"
            ]
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/databundles:read"
            ]
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/databundles:write"
            ]
          }
        ]
      }
    },
    "/models/{modelId}/trainings": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:read"
            ]
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:write"
            ]
          }
        ]
      }
    },
    "/models/{modelId}/trainings/{trainingId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/predictions:read"
            ]
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/predictions:write"
            ]
          }
        ]
      }
    },
    "/organizations": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/organizations:read"
            ]
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/organizations:write"
            ]
          }
        ]
      }
    },
    "/organizations/{organizationId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/organizations:read"
            ]
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/organizations:write"
            ]
          }
        ]
      }
    },
    "/paymentMethods": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/paymentmethods:read"
            ]
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/paymentmethods:write"
            ]
          }
        ]
      }
    },
    "/paymentMethods/{paymentMethodId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/paymentmethods:read"
            ]
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/paymentmethods:read"
            ]
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/paymentmethods:write"
            ]
          }
        ]
      }
    },
    "/plans": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/plans:read"
            ]
          }
        ]
      },
      "options": {
      }
    },
    "/plans/{planId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/plans:read"
            ]
          }
        ]
      },
      "options": {
      }
    },
    "/predictions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/predictions:read"
            ]
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/predictions:write"
            ]
          }
        ]
      }
    },
    "/profiles/{profileId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:read"
            ]
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:write"
            ]
          }
        ]
      }
    },
    "/roles": {
      "get": {
        "security": []
      },
      "options": {
      }
    },
    "/roles/{roleId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          }
        ]
      },
      "options": {
      }
    },
    "/secrets": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/secrets:read"
            ]
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/secrets:write"
            ]
          }
        ]
      }
    },
    "/secrets/{secretId}": {
      "delete": {
        "security": []
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/secrets:write"
            ]
          }
        ]
      }
    },
    "/transitions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions:read"
            ]
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions:write"
            ]
          }
        ]
      }
    },
    "/transitions/{transitionId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions:read"
            ]
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions:read"
            ]
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions:write"
            ]
          }
        ]
      }
    },
    "/transitions/{transitionId}/executions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.executions:read"
            ]
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.executions:write"
            ]
          }
        ]
      }
    },
    "/transitions/{transitionId}/executions/{executionId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.executions:read"
            ]
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.executions:write"
            ]
          }
        ]
      }
    },
    "/transitions/{transitionId}/executions/{executionId}/heartbeats": {
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.executions.heartbeats:write"
            ]
          }
        ]
      }
    },
    "/users": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:read"
            ]
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:write"
            ]
          }
        ]
      }
    },
    "/users/{userId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:read"
            ]
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:read"
            ]
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:write"
            ]
          }
        ]
      }
    },
    "/workflows": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:read"
            ]
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:write"
            ]
          }
        ]
      }
    },
    "/workflows/{workflowId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:read"
            ]
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:read"
            ]
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:write"
            ]
          }
        ]
      }
    },
    "/workflows/{workflowId}/executions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:read"
            ]
          }
        ]
      },
      "options": {
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:write"
            ]
          }
        ]
      }
    },
    "/workflows/{workflowId}/executions/{executionId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:read"
            ]
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:read"
            ]
          }
        ]
      },
      "options": {
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:write"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://auth.lucidtech.ai/oauth2/token",
            "scopes": {
              "api.lucidtech.ai/appclients:read": "Read permissions",
              "api.lucidtech.ai/appclients:write": "Write permissions",
              "api.lucidtech.ai/assets:read": "Read permissions",
              "api.lucidtech.ai/assets:write": "Write permissions",
              "api.lucidtech.ai/databundles:read": "Read permissions",
              "api.lucidtech.ai/databundles:write": "Write permissions",
              "api.lucidtech.ai/datasets:read": "Read permissions",
              "api.lucidtech.ai/datasets:write": "Write permissions",
              "api.lucidtech.ai/deploymentenvironments:read": "Read permissions",
              "api.lucidtech.ai/documents:read": "Read permissions",
              "api.lucidtech.ai/documents:write": "Write permissions",
              "api.lucidtech.ai/logs:read": "Read permissions",
              "api.lucidtech.ai/models:read": "Read permissions",
              "api.lucidtech.ai/models:write": "Write permissions",
              "api.lucidtech.ai/organizations:read": "Read permissions",
              "api.lucidtech.ai/organizations:write": "Write permissions",
              "api.lucidtech.ai/paymentmethods:read": "Read permissions",
              "api.lucidtech.ai/paymentmethods:write": "Write permissions",
              "api.lucidtech.ai/plans:read": "Read permissions",
              "api.lucidtech.ai/predictions:read": "Read permissions",
              "api.lucidtech.ai/predictions:write": "Write permissions",
              "api.lucidtech.ai/profiles:read": "Read permissions",
              "api.lucidtech.ai/profiles:write": "Write permissions",
              "api.lucidtech.ai/roles:read": "Read permissions",
              "api.lucidtech.ai/secrets:read": "Read permissions",
              "api.lucidtech.ai/secrets:write": "Write permissions",
              "api.lucidtech.ai/trainings:read": "Read permissions",
              "api.lucidtech.ai/trainings:write": "Write permissions",
              "api.lucidtech.ai/transformations:read": "Read permissions",
              "api.lucidtech.ai/transformations:write": "Write permissions",
              "api.lucidtech.ai/transitions.executions.heartbeats:write": "Write permissions",
              "api.lucidtech.ai/transitions.executions:read": "Read permissions",
              "api.lucidtech.ai/transitions.executions:write": "Write permissions",
              "api.lucidtech.ai/transitions:read": "Read permissions",
              "api.lucidtech.ai/transitions:write": "Write permissions",
              "api.lucidtech.ai/users:read": "Read permissions",
              "api.lucidtech.ai/users:write": "Write permissions",
              "api.lucidtech.ai/workflows.executions:read": "Read permissions",
              "api.lucidtech.ai/workflows.executions:write": "Write permissions",
              "api.lucidtech.ai/workflows:read": "Read permissions",
              "api.lucidtech.ai/workflows:write": "Write permissions"
            }
          }
        }
      }
    }
  }
}