name: Transition tests

on: [ pull_request ]

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/workflows/transitions/preprocess/requirements.txt
          pip install -r docs/workflows/transitions/postprocess/requirements.txt
          pip install pytest requests-mock~=1.11.0

      - name: Check Python code style
        run: |
          flake8 --ignore=E124

      - name: Run preprocess tests with pytest
        env:
          LAS_CLIENT_ID: test
          LAS_CLIENT_SECRET: test
          LAS_AUTH_ENDPOINT: test
          LAS_API_ENDPOINT: http://127.0.0.1:4010
        run: |
          pytest -v docs/workflows/transitions/preprocess/tests

      - name: Run postprocess tests with pytest
        env:
          LAS_CLIENT_ID: test
          LAS_CLIENT_SECRET: test
          LAS_AUTH_ENDPOINT: test
          LAS_API_ENDPOINT: http://127.0.0.1:4010
        run: |
          pytest -v docs/workflows/transitions/postprocess/tests
