name: Transition tests

on: [ pull_request ]

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/workflows/transitions/preprocess/requirements.txt

      - name: Test with pytest
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pip install pytest
          pytest -v docs/workflows/transitions/preprocess/tests

#      - name: Set up Poetry
#        uses: snok/install-poetry@v1
#        with:
#          version: 1.3.2

#      - name: Install dependencies
#        run: |
#          poetry config http-basic.lucidtech-pypi-repo ${{ secrets.PIP_USERNAME }} ${{ secrets.PIP_PASSWORD }}
#          poetry install
#          poetry run pip install -e .

#      - name: Check code style
#        run: |
#          poetry run flake8

#      - name: Run unittests with pytest
#        env:
#          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        run: |
#          poetry run pytest -v -n auto tests/unittests
