name: Update SDK references

on:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prerequisites
        run: |
          sudo apt-get install doxygen
          sudo apt-get install nodejs
          npm install moxygen

      - name: Check out python sdk
        uses: actions/checkout@master
        with:
          repository: LucidtechAI/las-sdk-python
          path: python-sdk

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Python SDK
        run: |
          cd python-sdk
          pip install -r requirements.docs.txt
          pip install tox
          make docs
          rm -rf ../static/python-docs/
          mv docs ../static/python-docs
          git add ../static/python-docs

      - name: Check out java sdk
        uses: actions/checkout@master
        with:
          repository: LucidtechAI/las-sdk-java
          path: java-sdk

      - name: Java SDK
        run: |
          cd java-sdk
          doxygen
          rm -rf ../static/java-docs/
          mv html ../static/java-docs
          git add ../static/java-docs

      - name: Check out .NET sdk
        uses: actions/checkout@master
        with:
          repository: LucidtechAI/las-sdk-net
          path: net-sdk

      - name: .NET SDK
        run: |
          cd net-sdk
          doxygen
          rm -rf ../static/dotnet-docs/
          mv html ../static/dotnet-docs
          git add ../static/dotnet-docs

      - name: Check out java-script sdk
        uses: actions/checkout@master
        with:
          repository: LucidtechAI/las-sdk-js
          path: js-sdk

      - name: JavaScript SDK
        run: |
          cd js-sdk
          npm install && npm run upgrade-lucidtech
          npm run docs
          # Remove links to source code lines
          sed -i -E -e '/Defined in.*/d' -e '/\[.+\]\(.+#L.+\)/d' docs.md
          mv docs.md ../docs/reference/sdks/js/latest.md

      - name: Clean up
        run: |
          rm -rf java-sdk
          rm -rf python-sdk
          rm -rf js-sdk
          rm -rf net-sdk
          rm package-lock.json
          rm -rf node_modules

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update SDK reference docs
          title: Update SDK reference docs
          body: This is an auto-generated PR with updated docs from the SDK.
          labels: automated pr
          branch: auto/update-sdk-reference
          base: master

